name: my_weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  device_preview: ^1.2.0

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/weather.jpg" # Corrected typo in the image path
  min_sdk_android: 21 # Corrected typo 'andriod' to 'android'
  remove_alpha_ios: true

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
